name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build_and_deploy_app1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App1
        run: |
          cd app1
          npm install
          ng build --configuration production --output-path ../dist/app1
      - name: Deploy App1
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_PLANT_02457D21E }}
          app_location: "/app1" # Relative to the root of the repo
          output_location: "dist/app1" # Relative to the app_location or root
          api_location: "" # If no API for this app

  build_and_deploy_app2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build App2
        run: |
          cd app2
          npm install
          ng build --configuration production --output-path ../dist/app2
      - name: Deploy App2
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_PLANT_02457D21E }}
          app_location: "/app2"
          output_location: "dist/app2"
          api_location: ""
